// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3OH3svQ3Bq2s_Kmmy8QrNL5bilAbXjjs',
    appId: '1:430060484059:web:20eab675fc0112fa3ce3fe',
    messagingSenderId: '430060484059',
    projectId: 'akromjon-a291b',
    authDomain: 'akromjon-a291b.firebaseapp.com',
    storageBucket: 'akromjon-a291b.appspot.com',
    measurementId: 'G-J7E9GBWH3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FVUCEFRib3X-gDZMRkkDz93xvjx3KrA',
    appId: '1:430060484059:android:bff8f42c8cb504843ce3fe',
    messagingSenderId: '430060484059',
    projectId: 'akromjon-a291b',
    storageBucket: 'akromjon-a291b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlZa4G-yyswblB2JtM5gdTEOfQjMf88A',
    appId: '1:430060484059:ios:f6b76b4ba6a3de1a3ce3fe',
    messagingSenderId: '430060484059',
    projectId: 'akromjon-a291b',
    storageBucket: 'akromjon-a291b.appspot.com',
    iosBundleId: 'com.example.lesson65',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlZa4G-yyswblB2JtM5gdTEOfQjMf88A',
    appId: '1:430060484059:ios:f6b76b4ba6a3de1a3ce3fe',
    messagingSenderId: '430060484059',
    projectId: 'akromjon-a291b',
    storageBucket: 'akromjon-a291b.appspot.com',
    iosBundleId: 'com.example.lesson65',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3OH3svQ3Bq2s_Kmmy8QrNL5bilAbXjjs',
    appId: '1:430060484059:web:2a64014ce2b3bde13ce3fe',
    messagingSenderId: '430060484059',
    projectId: 'akromjon-a291b',
    authDomain: 'akromjon-a291b.firebaseapp.com',
    storageBucket: 'akromjon-a291b.appspot.com',
    measurementId: 'G-DGN3B6NQ5K',
  );
}
